language: java

jdk:
  - openjdk7
  - oraclejdk7

env:
  global:
    - secure: "NZJ+d+nZK7S+LJrF2BljLJC/EXYINEP3qAuNpZ5khgSxammFN16FUlCnL/CgWPH5UyN0HdcF1COhwiP/veKaMBig9MGSvKa1ywuCVwMeQ39nPzVBdXt1QpnaBWNfOb3Teh6s3jx80vd2Asj6JCI+TFc0Bjg1wkibueRGXGpwATA="
    - secure: "OMoZaJHiaIYzBjhEjuMXHehsfKJfJUTpmYqBozs6WPGEFwPduFtYPBNHr5UZSS4hejNc6EePAljxbc3eydQH4K7rGRYaKk1PmPy7gRqZzHVgsxmnjvnY+8Xw42WSnzmDoNs7keZaa9UlRmocWyyXuDW0Y6zuYlJo3rz0hGJv0OQ="

before_script: echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>ketoth.xupack</username><password>${SONATYPE_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
script: mvn -e -DrepoToken=$COVERALLS_KEY clean install site
after_success: mvn deploy
